name: labs-validator
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  labs-validator:
    name: Labs Validator
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Labs Validator
        uses: safestack-hq/labs-action@v0.0.5
        env:
          LABS_AUTH: '${{secrets.LABS_AUTH}}'

